/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.71
 * Generated at: 2023-07-31 03:00:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class search_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1672628296113L));
    _jspx_dependants.put("jar:file:/C:/lks/springworkspaces/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/cineScope/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>써치 페이지</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<h3> 원하는 영화 검색을 원하시면 영화 제목을 입력하세요</h3>\r\n");
      out.write("	<form action=\"search/name\" method=\"get\">\r\n");
      out.write("		영화 제목 <input type=\"text\" name=\"m_name\"><br>\r\n");
      out.write("		영화 개봉일 \r\n");
      out.write("		<select name=\"m_opening\">\r\n");
      out.write("			<option value=\"1900\" selected> 전체</option>\r\n");
      out.write("			<option value=\"1990\" > 1990년대이후</option>\r\n");
      out.write("			<option value=\"2000\" > 2000년대이후</option>\r\n");
      out.write("			<option value=\"2010\" > 2010년대이후</option>\r\n");
      out.write("			<option value=\"2020\" > 2020년대이후</option>\r\n");
      out.write("		</select><br>\r\n");
      out.write("		<input type=\"hidden\" value=\"\" name=\"m_reopening\">\r\n");
      out.write("		영화 상영시간 <input type=\"text\" name=\"m_runtime\"><br>\r\n");
      out.write("		영화 평점 <input type=\"text\" name=\"m_grade\"><br>\r\n");
      out.write("		영화 감독 <input type=\"text\" name=\"m_director\"><br>\r\n");
      out.write("		영화 배우 <input type=\"text\" name=\"m_actor\"><br>\r\n");
      out.write("		영화 관객수 <input type=\"text\" name=\"m_attendance\"><br>\r\n");
      out.write("		영화 수상 <input type=\"text\" name=\"m_awards\"><br>\r\n");
      out.write("		영화 장르\r\n");
      out.write("		<select name=\"m_genre\">\r\n");
      out.write("			<option value=\"SF\" selected> SF</option>\r\n");
      out.write("			<option value=\"가족\" > 가족</option>\r\n");
      out.write("			<option value=\"공연\" > 공연</option>\r\n");
      out.write("			<option value=\"공포\" > 공포</option>\r\n");
      out.write("			<option value=\"다큐멘터리\" > 다큐멘터리</option>\r\n");
      out.write("			<option value=\"드라마\" > 드라마</option>\r\n");
      out.write("			<option value=\"로맨스\" > 로맨스</option>\r\n");
      out.write("			<option value=\"멜로\" > 멜로</option>\r\n");
      out.write("			<option value=\"뮤지컬\" > 뮤지컬</option>\r\n");
      out.write("			<option value=\"무협\" > 무협</option>\r\n");
      out.write("			<option value=\"미스터리\" > 미스터리</option>\r\n");
      out.write("			<option value=\"범죄\" > 범죄</option>\r\n");
      out.write("			<option value=\"서부\" > 서부</option>\r\n");
      out.write("			<option value=\"성인\" > 성인</option>\r\n");
      out.write("			<option value=\"스릴러\" > 스릴러</option>\r\n");
      out.write("			<option value=\"시대극\" > 시대극</option>\r\n");
      out.write("			<option value=\"애니메이션\" > 애니메이션</option>\r\n");
      out.write("			<option value=\"액션\" > 액션</option>\r\n");
      out.write("			<option value=\"어드벤처\" > 어드벤처</option>\r\n");
      out.write("			<option value=\"전쟁\" > 전쟁</option>\r\n");
      out.write("			<option value=\"코미디\" > 코미디</option>\r\n");
      out.write("			<option value=\"판타지\" > 판타지</option>\r\n");
      out.write("		</select>\r\n");
      out.write("		<br>\r\n");
      out.write("		\r\n");
      out.write("		영화 관람연령 \r\n");
      out.write("		<select name=\"m_age\">\r\n");
      out.write("			<option value=\"-1\" selected> 모든 ㄴ연령 관람가</option>\r\n");
      out.write("			<option value=\"0\" > 전체연령 관람가</option>\r\n");
      out.write("			<option value=\"12\" > 12세이상 관람가</option>\r\n");
      out.write("			<option value=\"15\" > 15세이상 관람가</option>\r\n");
      out.write("			<option value=\"18\" > 18세이상 관람가</option>\r\n");
      out.write("		</select>\r\n");
      out.write("		<br>\r\n");
      out.write("		영화 국가 \r\n");
      out.write("		<select name=\"m_nation\">\r\n");
      out.write("			<option value=\"나이지리아\" > 나이지리아</option>\r\n");
      out.write("			<option value=\"네덜란드\" > 네덜란드</option>\r\n");
      out.write("			<option value=\"노르웨이\" > 노르웨이</option>\r\n");
      out.write("			<option value=\"대만\" > 대만</option>\r\n");
      out.write("			<option value=\"덴마크\" > 덴마크</option>\r\n");
      out.write("			<option value=\"독일\" > 독일</option>\r\n");
      out.write("			<option value=\"라트비아\" > 러시아</option>\r\n");
      out.write("			<option value=\"루마니아\" > 루마니아</option>\r\n");
      out.write("			<option value=\"멕시코\" > 멕시코</option>\r\n");
      out.write("			<option value=\"미국\" > 미국</option>\r\n");
      out.write("			<option value=\"벨기에\" > 벨기에</option>\r\n");
      out.write("			<option value=\"브라질\" > 브라질</option>\r\n");
      out.write("			<option value=\"스웨덴\" > 스웨덴</option>\r\n");
      out.write("			<option value=\"아일랜드\" > 아르헨티나</option>\r\n");
      out.write("			<option value=\"영국\" > 영국</option>\r\n");
      out.write("			<option value=\"오스트레일리아\" > 오스트레일리아</option>\r\n");
      out.write("			<option value=\"오스트리아\" > 오스트리아</option>\r\n");
      out.write("			<option value=\"우크라이나\" > 우크라이나</option>\r\n");
      out.write("			<option value=\"유고슬라비아\" > 유고슬라비아</option>\r\n");
      out.write("			<option value=\"이탈리아\" > 이탈리아</option>\r\n");
      out.write("			<option value=\"인도\" > 인도</option>\r\n");
      out.write("			<option value=\"인도네시아\" > 인도네시아</option>\r\n");
      out.write("			<option value=\"일본\" > 일본</option>\r\n");
      out.write("			<option value=\"중국\" > 중국</option>\r\n");
      out.write("			<option value=\"캐나다\" > 캐나다</option>\r\n");
      out.write("			<option value=\"태국\" > 태국</option>\r\n");
      out.write("			<option value=\"터키\" > 터키</option>\r\n");
      out.write("			<option value=\"프랑스\" > 프랑스</option>\r\n");
      out.write("			<option value=\"핀란드\" > 핀란드</option>\r\n");
      out.write("			<option value=\"한국\" selected>한국</option>\r\n");
      out.write("			<option value=\"홍콩\" > 홍콩</option>\r\n");
      out.write("			\r\n");
      out.write("		</select>\r\n");
      out.write("		<br>\r\n");
      out.write("		<p></p>\r\n");
      out.write("		<input type=\"submit\" value=\"제출\">\r\n");
      out.write("	</form>\r\n");
      out.write("\r\n");
      out.write("	<h3> 연령별 영화 목록 검색을 원하시면 한가지를 선택하세요</h3>\r\n");
      out.write("	<form action=\"search/age\" method=\"get\">\r\n");
      out.write("		<select name=\"m_age\">\r\n");
      out.write("			<option value=\"0\" selected> 전체연령 관람가</option>\r\n");
      out.write("			<option value=\"12\" > 12세이상 관람가</option>\r\n");
      out.write("			<option value=\"15\" > 15세이상 관람가</option>\r\n");
      out.write("			<option value=\"18\" > 18세이상 관람가</option>\r\n");
      out.write("		</select>\r\n");
      out.write("		<p></p>\r\n");
      out.write("		<input type=\"submit\" value=\"제출\">\r\n");
      out.write("	</form>\r\n");
      out.write("	<h3> 장르별 영화 목록 검색을 원하시면 한가지를 선택하세요</h3>\r\n");
      out.write("	<form action=\"search/genre\" method=\"get\">\r\n");
      out.write("		<select name=\"m_genre\">\r\n");
      out.write("			<option value=\"SF\" selected> SF</option>\r\n");
      out.write("			<option value=\"가족\" > 가족</option>\r\n");
      out.write("			<option value=\"공연\" > 공연</option>\r\n");
      out.write("			<option value=\"공포\" > 공포</option>\r\n");
      out.write("			<option value=\"다큐멘터리\" > 다큐멘터리</option>\r\n");
      out.write("			<option value=\"드라마\" > 드라마</option>\r\n");
      out.write("			<option value=\"로맨스\" > 로맨스</option>\r\n");
      out.write("			<option value=\"멜로\" > 멜로</option>\r\n");
      out.write("			<option value=\"뮤지컬\" > 뮤지컬</option>\r\n");
      out.write("			<option value=\"무협\" > 무협</option>\r\n");
      out.write("			<option value=\"미스터리\" > 미스터리</option>\r\n");
      out.write("			<option value=\"범죄\" > 범죄</option>\r\n");
      out.write("			<option value=\"서부\" > 서부</option>\r\n");
      out.write("			<option value=\"성인\" > 성인</option>\r\n");
      out.write("			<option value=\"스릴러\" > 스릴러</option>\r\n");
      out.write("			<option value=\"시대극\" > 시대극</option>\r\n");
      out.write("			<option value=\"애니메이션\" > 애니메이션</option>\r\n");
      out.write("			<option value=\"액션\" > 액션</option>\r\n");
      out.write("			<option value=\"어드벤처\" > 어드벤처</option>\r\n");
      out.write("			<option value=\"전쟁\" > 전쟁</option>\r\n");
      out.write("			<option value=\"코미디\" > 코미디</option>\r\n");
      out.write("			<option value=\"판타지\" > 판타지</option>\r\n");
      out.write("		</select>\r\n");
      out.write("		<p></p>\r\n");
      out.write("		<input type=\"submit\" value=\"제출\">\r\n");
      out.write("	</form>\r\n");
      out.write("	<h3> 국가별 영화 목록 검색을 원하시면 한가지를 선택하세요</h3>\r\n");
      out.write("	<form action=\"search/nation\" method=\"get\">\r\n");
      out.write("		<select name=\"m_nation\">\r\n");
      out.write("			<option value=\"나이지리아\" > 나이지리아</option>\r\n");
      out.write("			<option value=\"네덜란드\" > 네덜란드</option>\r\n");
      out.write("			<option value=\"노르웨이\" > 노르웨이</option>\r\n");
      out.write("			<option value=\"대만\" > 대만</option>\r\n");
      out.write("			<option value=\"덴마크\" > 덴마크</option>\r\n");
      out.write("			<option value=\"독일\" > 독일</option>\r\n");
      out.write("			<option value=\"라트비아\" > 러시아</option>\r\n");
      out.write("			<option value=\"루마니아\" > 루마니아</option>\r\n");
      out.write("			<option value=\"멕시코\" > 멕시코</option>\r\n");
      out.write("			<option value=\"미국\" > 미국</option>\r\n");
      out.write("			<option value=\"벨기에\" > 벨기에</option>\r\n");
      out.write("			<option value=\"브라질\" > 브라질</option>\r\n");
      out.write("			<option value=\"스웨덴\" > 스웨덴</option>\r\n");
      out.write("			<option value=\"아일랜드\" > 아르헨티나</option>\r\n");
      out.write("			<option value=\"영국\" > 영국</option>\r\n");
      out.write("			<option value=\"오스트레일리아\" > 오스트레일리아</option>\r\n");
      out.write("			<option value=\"오스트리아\" > 오스트리아</option>\r\n");
      out.write("			<option value=\"우크라이나\" > 우크라이나</option>\r\n");
      out.write("			<option value=\"유고슬라비아\" > 유고슬라비아</option>\r\n");
      out.write("			<option value=\"이탈리아\" > 이탈리아</option>\r\n");
      out.write("			<option value=\"인도\" > 인도</option>\r\n");
      out.write("			<option value=\"인도네시아\" > 인도네시아</option>\r\n");
      out.write("			<option value=\"일본\" > 일본</option>\r\n");
      out.write("			<option value=\"중국\" > 중국</option>\r\n");
      out.write("			<option value=\"캐나다\" > 캐나다</option>\r\n");
      out.write("			<option value=\"태국\" > 태국</option>\r\n");
      out.write("			<option value=\"터키\" > 터키</option>\r\n");
      out.write("			<option value=\"프랑스\" > 프랑스</option>\r\n");
      out.write("			<option value=\"핀란드\" > 핀란드</option>\r\n");
      out.write("			<option value=\"한국\" selected>한국</option>\r\n");
      out.write("			<option value=\"홍콩\" > 홍콩</option>\r\n");
      out.write("			\r\n");
      out.write("		</select>\r\n");
      out.write("		<p></p>\r\n");
      out.write("		<input type=\"submit\" value=\"제출\">\r\n");
      out.write("	</form>\r\n");
      out.write("	\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
