/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.71
 * Generated at: 2023-08-01 05:11:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class searchresult_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(7);
    _jspx_dependants.put("/WEB-INF/views/include/sidebar.jsp", Long.valueOf(1690866554505L));
    _jspx_dependants.put("/WEB-INF/views/include/footer.jsp", Long.valueOf(1690858450923L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1672628296113L));
    _jspx_dependants.put("/WEB-INF/views/include/top.jsp", Long.valueOf(1690858602478L));
    _jspx_dependants.put("jar:file:/C:/lks/springworkspaces/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/cineScope/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/include/head.jsp", Long.valueOf(1690858417113L));
    _jspx_dependants.put("/WEB-INF/views/include/js.jsp", Long.valueOf(1690859280809L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("  \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("   \r\n");
      out.write("      <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("      <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("      <meta name=\"description\" content=\"Askbootstrap\">\r\n");
      out.write("      <meta name=\"author\" content=\"Askbootstrap\">\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      <!-- Favicon Icon -->\r\n");
      out.write("      <link rel=\"icon\" type=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/image/png\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/favicon.png\">\r\n");
      out.write("      \r\n");
      out.write("      <!-- Bootstrap core CSS-->\r\n");
      out.write("      <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("      <!-- Custom fonts for this template-->\r\n");
      out.write("      <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/vendor/fontawesome-free/css/all.min.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("      <!-- Custom styles for this template-->\r\n");
      out.write("      <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/osahan.css\" rel=\"stylesheet\">\r\n");
      out.write("      <!-- Owl Carousel -->\r\n");
      out.write("      <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/vendor/owl-carousel/owl.carousel.css\">\r\n");
      out.write("      <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/vendor/owl-carousel/owl.theme.css\">\r\n");
      out.write("      ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<title>search 결과 보여주는 화면</title>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("   ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<nav\r\n");
      out.write("	class=\"navbar navbar-expand navbar-light bg-white static-top osahan-nav sticky-top\">\r\n");
      out.write("	&nbsp;&nbsp;\r\n");
      out.write("	<button class=\"btn btn-link btn-sm text-secondary order-1 order-sm-0\"\r\n");
      out.write("		id=\"sidebarToggle\">\r\n");
      out.write("		<i class=\"fas fa-bars\"></i>\r\n");
      out.write("	</button>\r\n");
      out.write("	&nbsp;&nbsp; <a class=\"navbar-brand mr-1\" href=\"home\"><img\r\n");
      out.write("		class=\"img-fluid\" alt=\"\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/logo.png\"></a>\r\n");
      out.write("	<!-- Navbar Search -->\r\n");
      out.write("	<form\r\n");
      out.write("		class=\"d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-5 my-2 my-md-0 osahan-navbar-search\">\r\n");
      out.write("		<div class=\"input-group\">\r\n");
      out.write("			<input type=\"text\" class=\"form-control\" placeholder=\"Search for...\">\r\n");
      out.write("			<div class=\"input-group-append\">\r\n");
      out.write("				<button class=\"btn btn-light\" type=\"button\">\r\n");
      out.write("					<i class=\"fas fa-search\"></i>\r\n");
      out.write("				</button>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</form>\r\n");
      out.write("	<!-- Navbar -->\r\n");
      out.write("	<ul class=\"navbar-nav ml-auto ml-md-0 osahan-right-navbar\">\r\n");
      out.write("		<li class=\"nav-item mx-1\"><a class=\"nav-link\" href=\"upload\">\r\n");
      out.write("				<i class=\"fas fa-plus-circle fa-fw\"></i> Upload Video\r\n");
      out.write("		</a></li>\r\n");
      out.write("		<li class=\"nav-item dropdown no-arrow mx-1\"><a\r\n");
      out.write("			class=\"nav-link dropdown-toggle\" href=\"#\" id=\"alertsDropdown\"\r\n");
      out.write("			role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\"\r\n");
      out.write("			aria-expanded=\"false\"> <i class=\"fas fa-bell fa-fw\"></i> <span\r\n");
      out.write("				class=\"badge badge-danger\">9+</span>\r\n");
      out.write("		</a>\r\n");
      out.write("			<div class=\"dropdown-menu dropdown-menu-right\"\r\n");
      out.write("				aria-labelledby=\"alertsDropdown\">\r\n");
      out.write("				<a class=\"dropdown-item\" href=\"#\"><i class=\"fas fa-fw fa-edit \"></i>\r\n");
      out.write("					&nbsp; Action</a> <a class=\"dropdown-item\" href=\"#\"><i\r\n");
      out.write("					class=\"fas fa-fw fa-headphones-alt \"></i> &nbsp; Another action</a>\r\n");
      out.write("				<div class=\"dropdown-divider\"></div>\r\n");
      out.write("				<a class=\"dropdown-item\" href=\"#\"><i class=\"fas fa-fw fa-star \"></i>\r\n");
      out.write("					&nbsp; Something else here</a>\r\n");
      out.write("			</div></li>\r\n");
      out.write("		<li class=\"nav-item dropdown no-arrow mx-1\"><a\r\n");
      out.write("			class=\"nav-link dropdown-toggle\" href=\"#\" id=\"messagesDropdown\"\r\n");
      out.write("			role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\"\r\n");
      out.write("			aria-expanded=\"false\"> <i class=\"fas fa-envelope fa-fw\"></i> <span\r\n");
      out.write("				class=\"badge badge-success\">7</span>\r\n");
      out.write("		</a>\r\n");
      out.write("			<div class=\"dropdown-menu dropdown-menu-right\"\r\n");
      out.write("				aria-labelledby=\"messagesDropdown\">\r\n");
      out.write("				<a class=\"dropdown-item\" href=\"#\"><i class=\"fas fa-fw fa-edit \"></i>\r\n");
      out.write("					&nbsp; Action</a> <a class=\"dropdown-item\" href=\"#\"><i\r\n");
      out.write("					class=\"fas fa-fw fa-headphones-alt \"></i> &nbsp; Another action</a>\r\n");
      out.write("				<div class=\"dropdown-divider\"></div>\r\n");
      out.write("				<a class=\"dropdown-item\" href=\"#\"><i class=\"fas fa-fw fa-star \"></i>\r\n");
      out.write("					&nbsp; Something else here</a>\r\n");
      out.write("			</div></li>\r\n");
      out.write("		<li class=\"nav-item dropdown no-arrow osahan-right-navbar-user\">\r\n");
      out.write("			<a class=\"nav-link dropdown-toggle user-dropdown-link\" href=\"#\"\r\n");
      out.write("			id=\"userDropdown\" role=\"button\" data-toggle=\"dropdown\"\r\n");
      out.write("			aria-haspopup=\"true\" aria-expanded=\"false\"> <img alt=\"Avatar\"\r\n");
      out.write("				src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/user.png\"> Osahan\r\n");
      out.write("		</a>\r\n");
      out.write("			<div class=\"dropdown-menu dropdown-menu-right\"\r\n");
      out.write("				aria-labelledby=\"userDropdown\">\r\n");
      out.write("				<a class=\"dropdown-item\" href=\"account\"><i\r\n");
      out.write("					class=\"fas fa-fw fa-user-circle\"></i> &nbsp; My Account</a> <a\r\n");
      out.write("					class=\"dropdown-item\" href=\"subscriptions\"><i\r\n");
      out.write("					class=\"fas fa-fw fa-video\"></i> &nbsp; Subscriptions</a> <a\r\n");
      out.write("					class=\"dropdown-item\" href=\"settings\"><i\r\n");
      out.write("					class=\"fas fa-fw fa-cog\"></i> &nbsp; Settings</a>\r\n");
      out.write("				<div class=\"dropdown-divider\"></div>\r\n");
      out.write("				<a class=\"dropdown-item\" href=\"#\" data-toggle=\"modal\"\r\n");
      out.write("					data-target=\"#logoutModal\"><i class=\"fas fa-fw fa-sign-out-alt\"></i>\r\n");
      out.write("					&nbsp; Logout</a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</li>\r\n");
      out.write("	</ul>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("      <div id=\"wrapper\">\r\n");
      out.write("         <!-- Sidebar -->\r\n");
      out.write("         ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<ul class=\"sidebar navbar-nav\">\r\n");
      out.write("	<li class=\"nav-item active\"><a class=\"nav-link\" href=\"/\">\r\n");
      out.write("			<i class=\"fas fa-fw fa-home\"></i> <span>Home</span>\r\n");
      out.write("	</a></li>\r\n");
      out.write("	<li class=\"nav-item\"><a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/search\">\r\n");
      out.write("			<i class=\"fas fa-fw fa-users\"></i> <span>영화조회</span>\r\n");
      out.write("	</a></li>\r\n");
      out.write("	<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("		href=\"single-channel.html\"> <i class=\"fas fa-fw fa-user-alt\"></i>\r\n");
      out.write("			<span>Single Channel</span>\r\n");
      out.write("	</a></li>\r\n");
      out.write("	<li class=\"nav-item\"><a class=\"nav-link\" href=\"video-page.html\">\r\n");
      out.write("			<i class=\"fas fa-fw fa-video\"></i> <span>Video Page</span>\r\n");
      out.write("	</a></li>\r\n");
      out.write("	<li class=\"nav-item\"><a class=\"nav-link\" href=\"upload-video.html\">\r\n");
      out.write("			<i class=\"fas fa-fw fa-cloud-upload-alt\"></i> <span>Upload\r\n");
      out.write("				Video</span>\r\n");
      out.write("	</a></li>\r\n");
      out.write("	<li class=\"nav-item dropdown\"><a class=\"nav-link dropdown-toggle\"\r\n");
      out.write("		href=\"#\" role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\"\r\n");
      out.write("		aria-expanded=\"false\"> <i class=\"fas fa-fw fa-folder\"></i> <span>Pages</span>\r\n");
      out.write("	</a>\r\n");
      out.write("		<div class=\"dropdown-menu\">\r\n");
      out.write("			<h6 class=\"dropdown-header\">Login Screens:</h6>\r\n");
      out.write("			<a class=\"dropdown-item\" href=\"login.html\">Login</a> <a\r\n");
      out.write("				class=\"dropdown-item\" href=\"register.html\">Register</a> <a\r\n");
      out.write("				class=\"dropdown-item\" href=\"forgot-password.html\">Forgot\r\n");
      out.write("				Password</a>\r\n");
      out.write("			<div class=\"dropdown-divider\"></div>\r\n");
      out.write("			<h6 class=\"dropdown-header\">Other Pages:</h6>\r\n");
      out.write("			<a class=\"dropdown-item\" href=\"404.html\">404 Page</a> <a\r\n");
      out.write("				class=\"dropdown-item\" href=\"blank.html\">Blank Page</a>\r\n");
      out.write("		</div></li>\r\n");
      out.write("	<li class=\"nav-item\"><a class=\"nav-link\" href=\"history-page.html\">\r\n");
      out.write("			<i class=\"fas fa-fw fa-history\"></i> <span>History Page</span>\r\n");
      out.write("	</a></li>\r\n");
      out.write("	<li class=\"nav-item dropdown\"><a class=\"nav-link dropdown-toggle\"\r\n");
      out.write("		href=\"categories.html\" role=\"button\" data-toggle=\"dropdown\"\r\n");
      out.write("		aria-haspopup=\"true\" aria-expanded=\"false\"> <i\r\n");
      out.write("			class=\"fas fa-fw fa-list-alt\"></i> <span>Categories</span>\r\n");
      out.write("	</a>\r\n");
      out.write("		<div class=\"dropdown-menu\">\r\n");
      out.write("			<a class=\"dropdown-item\" href=\"categories.html\">Movie</a> <a\r\n");
      out.write("				class=\"dropdown-item\" href=\"categories.html\">Music</a> <a\r\n");
      out.write("				class=\"dropdown-item\" href=\"categories.html\">Television</a>\r\n");
      out.write("		</div></li>\r\n");
      out.write("	<li class=\"nav-item channel-sidebar-list\">\r\n");
      out.write("		<h6>SUBSCRIPTIONS</h6>\r\n");
      out.write("		<ul>\r\n");
      out.write("			<li><a href=\"subscriptions.html\"> <img class=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img-fluid\"\r\n");
      out.write("					alt=\"\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/s1.png\"> Your Life\r\n");
      out.write("			</a></li>\r\n");
      out.write("			<li><a href=\"subscriptions.html\"> <img class=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img-fluid\"\r\n");
      out.write("					alt=\"\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/s2.png\"> Unboxing <span\r\n");
      out.write("					class=\"badge badge-warning\">2</span>\r\n");
      out.write("			</a></li>\r\n");
      out.write("			<li><a href=\"subscriptions.html\"> <img class=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img-fluid\"\r\n");
      out.write("					alt=\"\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/s3.png\"> Product / Service\r\n");
      out.write("			</a></li>\r\n");
      out.write("			<li><a href=\"subscriptions.html\"> <img class=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img-fluid\"\r\n");
      out.write("					alt=\"\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/s4.png\"> Gaming\r\n");
      out.write("			</a></li>\r\n");
      out.write("		</ul>\r\n");
      out.write("	</li>\r\n");
      out.write("</ul>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("         <div id=\"content-wrapper\">\r\n");
      out.write("            <div class=\"container-fluid upload-details\">\r\n");
      out.write("            <!-- 여기서 부터 본문 작성 -->\r\n");
      out.write("            	");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("	\r\n");
      out.write("            </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- /.container-fluid -->\r\n");
      out.write("            <!-- Sticky Footer -->\r\n");
      out.write("            ");
      out.write("\r\n");
      out.write("	   \r\n");
      out.write("<footer class=\"sticky-footer\">\r\n");
      out.write("               <div class=\"container\">\r\n");
      out.write("                  <div class=\"row no-gutters\">\r\n");
      out.write("                     <div class=\"col-lg-6 col-sm-6\">\r\n");
      out.write("                        <p class=\"mt-1 mb-0\"><strong class=\"text-dark\">Vidoe</strong>. \r\n");
      out.write("                           <small class=\"mt-0 mb-0\"><a class=\"text-primary\" target=\"_blank\" href=\"https://www.templatespoint.net/\">Templates Point</a>\r\n");
      out.write("                           </small>\r\n");
      out.write("                        </p>\r\n");
      out.write("                     </div>\r\n");
      out.write("                     <div class=\"col-lg-6 col-sm-6 text-right\">\r\n");
      out.write("                        <div class=\"app\">\r\n");
      out.write("                           <a href=\"#\"><img alt=\"\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/google.png\"></a>\r\n");
      out.write("                           <a href=\"#\"><img alt=\"\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/apple.png\"></a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                     </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </div>\r\n");
      out.write("            </footer></html>");
      out.write("\r\n");
      out.write("         </div>\r\n");
      out.write("         <!-- /.content-wrapper -->\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- /#wrapper -->\r\n");
      out.write("      <!-- Scroll to Top Button-->\r\n");
      out.write("      <a class=\"scroll-to-top rounded\" href=\"#page-top\">\r\n");
      out.write("      <i class=\"fas fa-angle-up\"></i>\r\n");
      out.write("      </a>\r\n");
      out.write("      <!-- Logout Modal-->\r\n");
      out.write("      <div class=\"modal fade\" id=\"logoutModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("         <div class=\"modal-dialog modal-sm modal-dialog-centered\" role=\"document\">\r\n");
      out.write("            <div class=\"modal-content\">\r\n");
      out.write("               <div class=\"modal-header\">\r\n");
      out.write("                  <h5 class=\"modal-title\" id=\"exampleModalLabel\">Ready to Leave?</h5>\r\n");
      out.write("                  <button class=\"close\" type=\"button\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("                  <span aria-hidden=\"true\">×</span>\r\n");
      out.write("                  </button>\r\n");
      out.write("               </div>\r\n");
      out.write("               <div class=\"modal-body\">Select \"Logout\" below if you are ready to end your current session.</div>\r\n");
      out.write("               <div class=\"modal-footer\">\r\n");
      out.write("                  <button class=\"btn btn-secondary\" type=\"button\" data-dismiss=\"modal\">Cancel</button>\r\n");
      out.write("                  <a class=\"btn btn-primary\" href=\"login.html\">Logout</a>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- Bootstrap core JavaScript-->\r\n");
      out.write("      ");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/vendor/jquery/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<!-- Core plugin JavaScript-->\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/vendor/jquery-easing/jquery.easing.min.js\"></script>\r\n");
      out.write("<!-- Owl Carousel -->\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/vendor/owl-carousel/owl.carousel.js\"></script>\r\n");
      out.write("<!-- Custom scripts for all pages-->\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/custom.js\"></script>");
      out.write("\r\n");
      out.write("   </body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/include/head.jsp(3,1) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("contextPath");
      // /WEB-INF/views/include/head.jsp(3,1) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/include/head.jsp(3,1) '${pageContext.request.contextPath }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/searchresult.jsp(18,13) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${movieList ne null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("	영화목록 화면<br>\r\n");
          out.write("	<hr>\r\n");
          out.write("	");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${movieList}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('\r');
          out.write('\n');
          out.write('	');
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }
}
